title:              David Lin
email:              lin.david@berkeley.edu
description:        David Lin's Website
author:             David Lin
baseurl:            ""
url:                "https://lin-david.github.io/"

# Social Profiles
twitter_username:   davidlin__
github_username:    lin-david
facebook_username:  thunderbirdavid
linkedin_username:  davidmlin

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
